### ISSUE TITLE
Bug: Machine Shop Table quest is not accepted

### ISSUE THREAD

**Issue by a1d4r** [JadedPacks/Agrarian-Skies-2#12]
## Bug Report
I cannot complete "Machine Shop Table" quest in "Assembly Line" branch. It requires Machinist's Workbench (1308:0) but a crafted workbench in my inventory has another ID: 2190:1

## Client Information
Modpack Version: 2.0.1
Single Player

**Comment by a1d4r** [comment]
The same thing is also with "Water from air" quest where I need to get Aqueous Accumulator 1307:8

**Comment by RubikMonat** [comment]
Similar issue with the Sawmill and the Pulverizer. Same with the Aqueous accumulator quest for me too.

**Comment by ghost** [comment]
This was fixed in https://github.com/JadedPacks/Agrarian-Skies-2/commit/abee2c38b2ec30be906146bd259dc7c749d49e7c

Please either download the questing file from the github repository, or wait till 2.0.2 ;D

**Comment by RubikMonat** [comment]
I downloaded it, tested it, doesn't work. Did you try completing several of the thermal expansion quests in sequence in the test? Maybe only the first machine counts and locks the rest out? 

I completed the item ducts and servos quests fine, I notice those have distinct difference in the ID where one is 1405 and another is 1407 etc, rather than the machines where they are all 1418 but with a different damage code. 

Maybe it should say instead 
"id": "ThermalExpansion:Machine:2",
or "id": "ThermalExpansion:Machine_2",
I'm not sure of the proper notation. 

Example the sawmill quest requirement is: 
"requiredItems": [
						{
							"id": "ThermalExpansion:Machine",
							"Count": 1,
							"OreDict": "",
							"Damage": 2
						}
					],
					"taskID": "bq_standard:retrieval",
					"index": 0
				}

Vs the ducts quest: 

"requiredItems": [
						{
							"id": "ThermalDynamics:ThermalDynamics_16",
							"Count": 1,
							"OreDict": "",
							"Damage": 1
						},
						{
							"id": "ThermalDynamics:ThermalDynamics_32",
							"Count": 1,
							"OreDict": "",
							"Damage": 1

**Comment by ghost** [comment]
Double checked, and should be fixed as of https://github.com/JadedPacks/Agrarian-Skies-2/commit/f6cc3d77387ed582dd0b45e4ac448b301719190c

**Comment by a1d4r** [comment]
Still not working. ([Screenshots](https://imgur.com/a/yS2aW7n))

**Comment by ghost** [comment]
Fexed ^-^

**Comment by a1d4r** [comment]
I guess I'm doing something wrong, but how can I update questbook? I copied DefaultQuests.json to Agrarian Skies 2/config/betterquesting, but the quest book doesn't seem to be updated.

**Comment by ghost** [comment]
Just run `/bq_admin default load`
